### PR TITLE
alignment fix for currency item

### LINKED ISSUE #378: wrong alignment of currency item in wallet page
currently looking this -

Screenshot 2022-02-12 at 11 48 23 AM

ideally should like ✨

Screenshot 2022-02-12 at 11 48 09 AM

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
Fixes #378

### CODE REVIEW

File: src/containers/main/UpgradeContainer/index.tsx [hunk 1]
```diff
@@ -201,7 +201,7 @@ export const UpgradeContainer: FC<IProps> = ({ address, balance }) => {
       <table className={styles.dextable}>
         <thead>
           <tr>
-            <td> Currency</td>
+            <td style={{ textAlign: 'left' }}> Currency</td>
```
Comment (bigint) [inline src/containers/main/UpgradeContainer/index.tsx:204]: @abhisheknaiidu can we move this to css file, we should try avoiding the use of inline 😅 🙇🏻

**Review by bigint — CHANGES_REQUESTED** [review]

**Review by bigint — APPROVED** [review]
LGTM 🚀
