### PR TITLE
fix: show referral name instead of id.

### LINKED ISSUE #671: Show Referral name not ID
Instead of showing `10` this should show affiliate ID 10's name, which is `carl`
Screen Shot 2022-05-20 at 3 36 53 PM

### PR DESCRIPTION
**Pull request by zhyd1997**
Fixes #671

### CODE REVIEW

File: src/containers/main/ReferContainer/index.tsx [hunk 1]
```diff
@@ -11,190 +11,201 @@ import { AFFILIATE_STATUS, filterValidationErrors, getAffiliateStatus } from 'ut
...
+				const contractMethods = await contract.methods;
+				const affiliate = await contractMethods.customerToAffiliate(address.toLowerCase()).call();
+				if (affiliate !== '0') {
+					const referral = await contractMethods.affiliates(affiliate).call();
+					if (isMounted) {
+						setReferredBy(referral.name);
+					}
+				}
+			})();
+		}
```
Comment (zhyd1997) [inline src/containers/main/ReferContainer/index.tsx:45]: the core logic is here.

**Comment by zhyd1997** [comment]
Hi @mikeghen 

This PR is ready for review now.

**Comment by mikeghen** [comment]
Screen Shot 2022-05-26 at 2 13 42 PM
LGTM, nicely done @zhyd1997

**Review by mikeghen — APPROVED** [review]
