### PR TITLE
fix: removed missing key prop warning.

### LINKED ISSUE #332: Fix missing `key` prop warning.
`/wallet` page

missing key prop

### PR DESCRIPTION
**Pull request by zhyd1997**
fixed #332

### CODE REVIEW

File: src/containers/main/UpgradeContainer/index.tsx [hunk 1]
```diff
@@ -280,7 +280,7 @@ export const UpgradeContainer: FC<IProps> = ({ address, balance }) => {
                 .times(usdPrice);
 
               return (
-                <tr>
+                <tr key={token.coin}>
```
Comment (zhyd1997) [inline src/containers/main/UpgradeContainer/index.tsx:283]: `token.coin` can be the `key` prop because it is **unique** and also **stable**.

**Review by mikeghen — APPROVED** [review]
good work, thanks!
